### ISSUE TITLE
no exception handling

### ISSUE THREAD

**Issue by DaveScream** [Automaticism/Promptvision#15]
C:\Software\Stable_Diffusion\PromptVision\venv\Lib\site-packages\PIL\Image.py:3167: DecompressionBombWarning: Image size (148897792 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.
  warnings.warn(
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python311\Lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Software\Stable_Diffusion\PromptVision\gallery.py", line 1019, in read_exif_data
    img = Image.open(image)
          ^^^^^^^^^^^^^^^^^
  File "C:\Software\Stable_Diffusion\PromptVision\venv\Lib\site-packages\PIL\Image.py", line 3283, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'C:\\Software\\Stable_Diffusion\\Images\\160.jpg'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Software\Stable_Diffusion\PromptVision\gallery.py", line 1197, in <module>
    bulk_exif_data = mp_bulk_exif_read(filtered_images)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\Stable_Diffusion\PromptVision\gallery.py", line 1117, in mp_bulk_exif_read
    row = result.get()
          ^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\pool.py", line 774, in get
    raise self._value
PIL.UnidentifiedImageError: cannot identify image file 'C:\\Software\\Stable_Diffusion\\Images\\160.jpg'

**Comment by Automaticism** [comment]
Thanks for the report.

You can try now. The limit is removed and now you should be able to load however large images you want.
