### ISSUE TITLE
Exceeded Memory Limit?

### ISSUE THREAD

**Issue by netdzynr** [Automaticism/Promptvision#34]
Installed on macos 13.5.1 using miniconda.
After setting default directory, image scan ran for several minutes and then appeared to dump metadata of all images in Terminal, with this error:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/runtime.py", line 596, in _loop_coroutine
    self._send_message(active_session_info, msg)
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/runtime.py", line 661, in _send_message
    populate_hash_if_needed(msg)
  File "/opt/homebrew/lib/python3.11/site-packages/streamlit/runtime/forward_msg_cache.py", line 59, in populate_hash_if_needed
    hasher.update(msg.SerializeToString())
                  ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Message ForwardMsg exceeds maximum protobuf size of 2GB: 4704277104

**Comment by Automaticism** [comment]
You can adjust the `--server.maxMessageSize 2048` on launch. Set e.g. 4096.

`streamlit run .\promptvision.py --server.maxMessageSize 2048`
