### ISSUE TITLE
Crashes During Launch

### ISSUE THREAD

**Issue by don1138** [Automaticism/Promptvision#4]
# App and OS versions

Promptvision v0.2
MacOS 13.2.1
32Gb M1 Max

# Describe the bug

I have a folder of images I've grabbed from model cards and other sources. Formats include PNG, JPG, and WebP. Some have EXIF data, others do not.

When I run the command, an exception crashes the process.

# How to Reproduce

Run  the command (on a similar system).

# Error message
### Command:
```
user@rig Promptvision % python gallery.py --imagedir /Users/user/-AI/REFERENCE/GRABS
```
### About 440 lines of this:
```
ERROR   2023-03-23 17:54:16,091 [ERROR][read_exif_data] line:879 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=755x1351 at 0x15A1F01D0>
ERROR   2023-03-23 17:54:16,091 [ERROR][read_exif_data] line:880 text
```
### And then this:
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Promptvision/gallery.py", line 885, in read_exif_data
    for key_value in exif_data['parameters'].split('\n'):
                     ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'parameters'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/Promptvision/gallery.py", line 1026, in <module>
    bulk_exif_data = mp_bulk_exif_read(filtered_images)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Promptvision/gallery.py", line 952, in mp_bulk_exif_read
    row = result.get()
          ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
KeyError: 'parameters'
```

# Screenshots

**Comment by Automaticism** [comment]
Fixed. Thanks for reporting!
